### ISSUE TITLE
can't run MM when your module is activ....

### ISSUE THREAD

**Issue by ROMSY-SAN** [deg0nz/MMM-PublicTransportBerlin#22] opened 2017-07-14 18:42 UTC
Hi, i just installed your module on my Raspberry Pi 1 (Model B) with Midori Browser.
unfortunately whenever i put your example in my config.js i can't run Magic Mirror anymore , i just get an error that the server can't be loaded. 
When i remove your example everything works like normal. Any way i can provide more info, so you can see why it doesn't work? (Or Tips what i should do?)

**Comment by deg0nz** [comment] 2017-07-15 10:10
Hey, the problem is, that this module needs NodeJS version > 6.0.0, because it uses Next generation Javascript features (ECMAScript 6).

Unfortunately the Midori Browser does not support these language features. So the module doesn't work in it :(

I can't really help you right now, because I have no access to my computer this weekend.

I can popose the following:
Try to use a Javascript transpiler like Babel to convert the code of the module to vanilla old javascript and see if it works.
(I'm not sure if this works though...)

If you need help by using a transpiler, please ask in the forum. I think many people are able to help you there. (Or be patient and wait until I get access to my computer again next week ;)

**Comment by ROMSY-SAN** [comment] 2017-07-15 14:09
hey thanks for the reply :)
i think waiting is the better option (or if i get inpatient i going to buy a new pi, so that my pi2 will work as Magic Mirror ;)

**Comment by deg0nz** [comment] 2017-07-15 22:42
Ok. I'd really recomment to buy a Raspberry Pi 3.
In my experience, the MagicMirror App runs much smoother on it. And you will be able to use the Onboard Wifi of the Pi 3.

**Comment by deg0nz** [comment] 2017-08-15 09:38
Since nothing happened here for more than a month now, and you mentionened a RPi3 in #23, I'm closing this now.

**Closed by deg0nz** 2017-08-15 09:38 UTC
